sudo: false

language: node_js

node_js:
  - '0.12'
  - '4'
  - '6'
  - '7'

branches:
  only:
    - master
    - travis-ci

before_install:
  # Echo trickery prevents an error return from `[ -e $dir/package.json ]` from erroring the Travis CI build.
  - for dir in $(find . -maxdepth 1 -type d -a ! -name .\*); do [ -e $dir/package.json ] && (cd $dir && npm install && echo $dir) || echo $dir; done
  - npm install
  - npm install istanbul coveralls
