sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '7'

branches:
  only:
    - master
    - travis-ci

before_install:
  - for dir in $(find . -maxdepth 1 -type d -a ! -name .\*); do [ -e $dir/package.json ] && (cd $dir && npm install); done
  - npm install
  - npm install istanbul coveralls
